#!/usr/bin/env python3
# ============================================================================
#  TEMPERATURE-GRADIENT ORIENTATION ANALYSIS
#
#  Produces the data behind Table 4 in the manuscript and addresses:
#    - Reviewer 2 Comment 3 ("Compute angular distribution of temperature
#                             gradient to reveal how the path asymmetry
#                             changes with p_spec.")
#
#  WHAT THIS SCRIPT DOES
#  ---------------------
#  Loads the two field NPZ files generated by the baseline solver runs at
#  p_spec = 0 and p_spec = 1 (created by `reproduce_paper.py` Stage 1).
#  For each (forward/reverse) x (p=0/p=1) combination, it computes the
#  per-cell gradient-orientation angle:
#
#      theta_grad(x,y) = atan( |dT/dy| / |dT/dx| )    in degrees
#      0 deg  = purely streamwise gradient
#      90 deg = purely transverse gradient
#
#  Summary statistics (mean, median, p90, fraction above 15/30/45 deg) are
#  computed for each case, and the L1 distance between the forward and
#  reverse distributions is used as a quantitative path-asymmetry metric.
#
#  Outputs:
#    gradient_orientation_summary.csv
#    gradient_orientation_asymmetry_metrics.csv
#    gradient_orientation_histograms.csv
#    Fig_revision_gradient_orientation.{png,pdf}
#
#  USAGE
#  -----
#    python analysis/gradient_orientation_analysis.py
#    python analysis/gradient_orientation_analysis.py \
#        --p0-file all_results/results_fields_compare/p_0.0/xc0.250_r0.230_a0.500_p0.000.npz \
#        --p1-file all_results/results_fields_compare/p_1.0/xc0.250_r0.230_a0.500_p1.000.npz
# ============================================================================

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def find_npz(search_root, filename):
    """Search recursively under `search_root` for a file named `filename`."""
    hits = list(Path(search_root).rglob(filename))
    return hits[0] if hits else None


def gradient_orientation_deg(T, mask, dx, dy):
    """Per-cell |dT/dy| / |dT/dx| angle in degrees, masking pore and border."""
    dTdx, dTdy = np.gradient(T, dx, dy, edge_order=2)
    theta = np.degrees(np.arctan2(np.abs(dTdy), np.abs(dTdx) + 1e-30))

    valid = (~mask).copy()
    # exclude the outer one-cell border to avoid boundary-condition artifacts
    valid[0, :] = False
    valid[-1, :] = False
    valid[:, 0] = False
    valid[:, -1] = False

    vals = theta[valid]
    return vals[np.isfinite(vals)]


def hist_distance(a, b, bins):
    """L1 distance between two empirical histograms (normalized as p.m.f.s)."""
    ha, _ = np.histogram(a, bins=bins, density=True)
    hb, _ = np.histogram(b, bins=bins, density=True)
    ha = ha / (ha.sum() + 1e-30)
    hb = hb / (hb.sum() + 1e-30)
    return 0.5 * np.sum(np.abs(ha - hb))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--p0-file", type=str, default=None,
                    help="Path to p_spec=0 NPZ. Auto-discovered if omitted.")
    ap.add_argument("--p1-file", type=str, default=None,
                    help="Path to p_spec=1 NPZ. Auto-discovered if omitted.")
    ap.add_argument("--search-root", type=str, default="all_results",
                    help="Where to search for NPZ files when paths not given.")
    ap.add_argument("--outdir", type=str,
                    default="all_results/revision_gradient_orientation",
                    help="Where to write CSV and figure outputs.")
    args = ap.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    # Resolve file locations
    p0 = Path(args.p0_file) if args.p0_file else find_npz(
        args.search_root, "xc0.250_r0.230_a0.500_p0.000.npz")
    p1 = Path(args.p1_file) if args.p1_file else find_npz(
        args.search_root, "xc0.250_r0.230_a0.500_p1.000.npz")

    if p0 is None or p1 is None:
        sys.exit("ERROR: could not locate baseline NPZ files. "
                 "Run reproduce_paper.py first, or pass --p0-file / --p1-file.")

    print(f"p=0 file: {p0}")
    print(f"p=1 file: {p1}")

    d0 = np.load(p0, allow_pickle=True)
    d1 = np.load(p1, allow_pickle=True)

    Tf_p0 = d0["Tf"].astype(float)
    Tr_p0 = d0["Tr"].astype(float)
    Tf_p1 = d1["Tf"].astype(float)
    Tr_p1 = d1["Tr"].astype(float)
    mask = d0["mask"].astype(bool)

    Nx, Ny = Tf_p0.shape
    dx = 1.0 / (Nx - 1)
    dy = 1.0 / (Ny - 1)
    print(f"Field shape: {Tf_p0.shape}   Solid fraction: {(~mask).mean():.4f}")

    cases = {
        "Forward, p=0": gradient_orientation_deg(Tf_p0, mask, dx, dy),
        "Reverse, p=0": gradient_orientation_deg(Tr_p0, mask, dx, dy),
        "Forward, p=1": gradient_orientation_deg(Tf_p1, mask, dx, dy),
        "Reverse, p=1": gradient_orientation_deg(Tr_p1, mask, dx, dy),
    }

    # Summary statistics
    summary = pd.DataFrame([
        dict(case=name, N_values=len(v),
             mean_theta_deg=v.mean(),
             median_theta_deg=np.median(v),
             p90_theta_deg=np.percentile(v, 90),
             frac_theta_gt_15deg=(v > 15.0).mean(),
             frac_theta_gt_30deg=(v > 30.0).mean(),
             frac_theta_gt_45deg=(v > 45.0).mean())
        for name, v in cases.items()
    ])

    bins = np.linspace(0, 90, 46)
    asymmetry = pd.DataFrame([
        dict(p_spec_case=p_label,
             abs_mean_theta_F_minus_R_deg=abs(cases[fk].mean() - cases[rk].mean()),
             abs_median_theta_F_minus_R_deg=abs(np.median(cases[fk]) - np.median(cases[rk])),
             histogram_L1_distance=hist_distance(cases[fk], cases[rk], bins))
        for (p_label, fk, rk) in [
            ("p=0", "Forward, p=0", "Reverse, p=0"),
            ("p=1", "Forward, p=1", "Reverse, p=1"),
        ]
    ])

    summary.to_csv(outdir / "gradient_orientation_summary.csv", index=False)
    asymmetry.to_csv(outdir / "gradient_orientation_asymmetry_metrics.csv", index=False)

    bin_centers = 0.5 * (bins[:-1] + bins[1:])
    hist_rows = []
    for name, v in cases.items():
        h, _ = np.histogram(v, bins=bins, density=True)
        for c, hh in zip(bin_centers, h):
            hist_rows.append(dict(case=name, theta_center_deg=c, density=hh))
    pd.DataFrame(hist_rows).to_csv(
        outdir / "gradient_orientation_histograms.csv", index=False)

    print("\n=== Gradient-orientation summary (Table 4) ===")
    print(summary.to_string(index=False))
    print("\n=== Forward/reverse path-asymmetry metrics ===")
    print(asymmetry.to_string(index=False))

    # Figure
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.9), constrained_layout=True)

    for ax, p_label, fkey, rkey, title in [
        (axes[0], "p=0", "Forward, p=0", "Reverse, p=0",
         r"(a) Diffuse wall, $p_{\mathrm{spec}}=0$"),
        (axes[1], "p=1", "Forward, p=1", "Reverse, p=1",
         r"(b) Specular wall, $p_{\mathrm{spec}}=1$"),
    ]:
        for key, style in [(fkey, "-"), (rkey, "--")]:
            h, _ = np.histogram(cases[key], bins=bins, density=True)
            ax.plot(bin_centers, h, style, linewidth=2, label=key)
        ax.set_xlabel(r"Gradient-orientation angle $\theta_{\mathrm{grad}}$ (deg)")
        ax.set_ylabel("Probability density")
        ax.set_title(title)
        ax.legend(frameon=False, fontsize=8)
        ax.grid(True, alpha=0.3)

    ax = axes[2]
    ax.bar(asymmetry["p_spec_case"], asymmetry["histogram_L1_distance"])
    ax.set_ylabel("Forward/reverse distribution distance")
    ax.set_title("(c) Path-asymmetry metric")
    ax.grid(True, axis="y", alpha=0.3)

    fig.savefig(outdir / "Fig_revision_gradient_orientation.png",
                dpi=300, bbox_inches="tight")
    fig.savefig(outdir / "Fig_revision_gradient_orientation.pdf",
                bbox_inches="tight")
    plt.close(fig)

    print(f"\nAll outputs saved under {outdir}/")


if __name__ == "__main__":
    main()
